spring:
  application:
    name: netflix-zuul-api-gateway-server

server:
  port: 8765


zuul:
  routes:
    currency-exchange-service:
      path: /currency-exchange/**
      serviceId: currency-exchange-service
      strip-prefix: false
    currency-conversion-service:
        path: /currency-converter/**
        serviceId: currency-conversion-service
        strip-prefix: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      ##defaultZone: http://ec2-18-223-159-199.us-east-2.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: localhost